Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We can then progress the glacier to equilibrium again
glacier.progress_to_equilibrium()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [18][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# We can then progress the glacier to equilibrium again[39;00m
[0;32m----> 2[0m [43mglacier[49m[38;5;241;43m.[39;49m[43mprogress_to_equilibrium[49m[43m([49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm_edu/glacier.py:527[0m, in [0;36mGlacier.progress_to_equilibrium[0;34m(self, years, t_rate)[0m
[1;32m    523[0m [38;5;28;01melse[39;00m:
[1;32m    524[0m     [38;5;66;03m# Do we have a temp scenario which isn't passed yet?[39;00m
[1;32m    525[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mage [38;5;241m<[39m [38;5;28mself[39m[38;5;241m.[39mmass_balance[38;5;241m.[39m_temp_bias_final_year:
[1;32m    526[0m         [38;5;66;03m# If so, progress normally.[39;00m
[0;32m--> 527[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mprogress_to_year[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmass_balance[49m[38;5;241;43m.[39;49m[43m_temp_bias_final_year[49m[43m)[49m
[1;32m    528[0m     [38;5;66;03m# Then we can find the eq. state.[39;00m
[1;32m    529[0m     [38;5;66;03m# Initialise the model[39;00m
[1;32m    530[0m     state [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_state()

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm_edu/glacier.py:438[0m, in [0;36mGlacier.progress_to_year[0;34m(self, year)[0m
[1;32m    435[0m         [38;5;28;01mreturn[39;00m
[1;32m    437[0m [38;5;66;03m# Update attributes.[39;00m
[0;32m--> 438[0m [38;5;28mself[39m[38;5;241m.[39mhistory [38;5;241m=[39m out[[38;5;241m0[39m]
[1;32m    439[0m [38;5;28mself[39m[38;5;241m.[39mstate_history [38;5;241m=[39m out[[38;5;241m1[39m][[38;5;241m0[39m]
[1;32m    440[0m [38;5;28mself[39m[38;5;241m.[39m_current_state [38;5;241m=[39m model[38;5;241m.[39mfls[[38;5;241m0[39m]

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm_edu/glacier.py:312[0m, in [0;36mGlacier.history[0;34m(self, obj)[0m
[1;32m    308[0m     [38;5;28mself[39m[38;5;241m.[39m_history [38;5;241m=[39m obj
[1;32m    309[0m [38;5;66;03m# Append the history.[39;00m
[1;32m    310[0m [38;5;28;01melse[39;00m:
[1;32m    311[0m     [38;5;66;03m# We slice the new series because we dont need the first year.[39;00m
[0;32m--> 312[0m     [38;5;28mself[39m[38;5;241m.[39m_history [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mcombine_by_coords[49m[43m([49m
[1;32m    313[0m [43m        [49m[43m[[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhistory[49m[38;5;241;43m.[39;49m[43misel[49m[43m([49m[43mtime[49m[38;5;241;43m=[39;49m[38;5;28;43mslice[39;49m[43m([49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[38;5;241;43m-[39;49m[38;5;241;43m1[39;49m[43m)[49m[43m)[49m[43m,[49m[43m [49m[43mobj[49m[43m][49m[43m,[49m
[1;32m    314[0m [43m        [49m[43mcombine_attrs[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43moverride[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    315[0m [43m    [49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/xarray/core/combine.py:975[0m, in [0;36mcombine_by_coords[0;34m(data_objects, compat, data_vars, coords, fill_value, join, combine_attrs, datasets)[0m
[1;32m    973[0m     concatenated_grouped_by_data_vars [38;5;241m=[39m []
[1;32m    974[0m     [38;5;28;01mfor[39;00m [38;5;28mvars[39m, datasets_with_same_vars [38;5;129;01min[39;00m grouped_by_vars:
[0;32m--> 975[0m         concatenated [38;5;241m=[39m [43m_combine_single_variable_hypercube[49m[43m([49m
[1;32m    976[0m [43m            [49m[38;5;28;43mlist[39;49m[43m([49m[43mdatasets_with_same_vars[49m[43m)[49m[43m,[49m
[1;32m    977[0m [43m            [49m[43mfill_value[49m[38;5;241;43m=[39;49m[43mfill_value[49m[43m,[49m
[1;32m    978[0m [43m            [49m[43mdata_vars[49m[38;5;241;43m=[39;49m[43mdata_vars[49m[43m,[49m
[1;32m    979[0m [43m            [49m[43mcoords[49m[38;5;241;43m=[39;49m[43mcoords[49m[43m,[49m
[1;32m    980[0m [43m            [49m[43mcompat[49m[38;5;241;43m=[39;49m[43mcompat[49m[43m,[49m
[1;32m    981[0m [43m            [49m[43mjoin[49m[38;5;241;43m=[39;49m[43mjoin[49m[43m,[49m
[1;32m    982[0m [43m            [49m[43mcombine_attrs[49m[38;5;241;43m=[39;49m[43mcombine_attrs[49m[43m,[49m
[1;32m    983[0m [43m        [49m[43m)[49m
[1;32m    984[0m         concatenated_grouped_by_data_vars[38;5;241m.[39mappend(concatenated)
[1;32m    986[0m [38;5;28;01mreturn[39;00m merge(
[1;32m    987[0m     concatenated_grouped_by_data_vars,
[1;32m    988[0m     compat[38;5;241m=[39mcompat,
[0;32m   (...)[0m
[1;32m    991[0m     combine_attrs[38;5;241m=[39mcombine_attrs,
[1;32m    992[0m )

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/xarray/core/combine.py:652[0m, in [0;36m_combine_single_variable_hypercube[0;34m(datasets, fill_value, data_vars, coords, compat, join, combine_attrs)[0m
[1;32m    650[0m     indexes [38;5;241m=[39m concatenated[38;5;241m.[39mindexes[38;5;241m.[39mget(dim)
[1;32m    651[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (indexes[38;5;241m.[39mis_monotonic_increasing [38;5;129;01mor[39;00m indexes[38;5;241m.[39mis_monotonic_decreasing):
[0;32m--> 652[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    653[0m             [38;5;124m"[39m[38;5;124mResulting object does not have monotonic[39m[38;5;124m"[39m
[1;32m    654[0m             [38;5;124m"[39m[38;5;124m global indexes along dimension [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(dim)
[1;32m    655[0m         )
[1;32m    657[0m [38;5;28;01mreturn[39;00m concatenated

[0;31mValueError[0m: Resulting object does not have monotonic global indexes along dimension time
ValueError: Resulting object does not have monotonic global indexes along dimension time

