Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
glacier.progress_to_equilibrium()
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[7][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mglacier[49m[43m.[49m[43mprogress_to_equilibrium[49m[43m([49m[43m)[49m

[36mFile [39m[32m/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/oggm_edu/glacier.py:674[39m, in [36mGlacier.progress_to_equilibrium[39m[34m(self, years, t_rate)[39m
[32m    671[39m [38;5;66;03m# Run the model.[39;00m
[32m    672[39m [38;5;28;01mtry[39;00m:
[32m    673[39m     [38;5;66;03m#  Run with a stopping criteria.[39;00m
[32m--> [39m[32m674[39m     out = [43mmodel[49m[43m.[49m[43mrun_until_and_store[49m[43m([49m
[32m    675[39m [43m        [49m[43myears[49m[43m,[49m[43m [49m[43mfl_diag_path[49m[43m=[49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[43mstop_criterion[49m[43m=[49m[43mstop_function[49m
[32m    676[39m [43m    [49m[43m)[49m
[32m    678[39m [38;5;28;01mexcept[39;00m [38;5;167;01mRuntimeError[39;00m:
[32m    679[39m     [38;5;66;03m# We chose to print and return instead of raising since the[39;00m
[32m    680[39m     [38;5;66;03m# collection will then be able to continue.[39;00m
[32m    681[39m     msg = [33m"[39m[33mGlacier grew out of its domain before reaching an equilibrium state.[39m[33m"[39m

[36mFile [39m[32m/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/oggm/core/flowline.py:1039[39m, in [36mFlowlineModel.run_until_and_store[39m[34m(self, y1, diag_path, fl_diag_path, geom_path, store_monthly_step, stop_criterion, fixed_geometry_spinup_yr, dynamic_spinup_min_ice_thick)[39m
[32m   1036[39m nm = [38;5;28mlen[39m(monthly_time)
[32m   1038[39m [38;5;28;01mif[39;00m do_geom [38;5;129;01mor[39;00m do_fl_diag:
[32m-> [39m[32m1039[39m     sects = [43m[[49m[43m([49m[43mnp[49m[43m.[49m[43mzeros[49m[43m([49m[43m([49m[43mny[49m[43m,[49m[43m [49m[43mfl[49m[43m.[49m[43mnx[49m[43m)[49m[43m)[49m[43m [49m[43m*[49m[43m [49m[43mnp[49m[43m.[49m[43mNaN[49m[43m)[49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mfl[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[38;5;28;43mself[39;49m[43m.[49m[43mfls[49m[43m][49m
[32m   1040[39m     widths = [(np.zeros((ny, fl.nx)) * np.NaN) [38;5;28;01mfor[39;00m fl [38;5;129;01min[39;00m [38;5;28mself[39m.fls]
[32m   1041[39m     buckets = [np.zeros(ny) [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mself[39m.fls]

[36mFile [39m[32m/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/oggm/core/flowline.py:1039[39m, in [36m<listcomp>[39m[34m(.0)[39m
[32m   1036[39m nm = [38;5;28mlen[39m(monthly_time)
[32m   1038[39m [38;5;28;01mif[39;00m do_geom [38;5;129;01mor[39;00m do_fl_diag:
[32m-> [39m[32m1039[39m     sects = [(np.zeros((ny, fl.nx)) * [43mnp[49m[43m.[49m[43mNaN[49m) [38;5;28;01mfor[39;00m fl [38;5;129;01min[39;00m [38;5;28mself[39m.fls]
[32m   1040[39m     widths = [(np.zeros((ny, fl.nx)) * np.NaN) [38;5;28;01mfor[39;00m fl [38;5;129;01min[39;00m [38;5;28mself[39m.fls]
[32m   1041[39m     buckets = [np.zeros(ny) [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mself[39m.fls]

[36mFile [39m[32m/usr/local/pyenv/versions/3.11.11/lib/python3.11/site-packages/numpy/__init__.py:400[39m, in [36m__getattr__[39m[34m(attr)[39m
[32m    397[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr], name=[38;5;28;01mNone[39;00m)
[32m    399[39m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __expired_attributes__:
[32m--> [39m[32m400[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[32m    401[39m         [33mf[39m[33m"[39m[33m`np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[33m` was removed in the NumPy 2.0 release. [39m[33m"[39m
[32m    402[39m         [33mf[39m[33m"[39m[38;5;132;01m{[39;00m__expired_attributes__[attr][38;5;132;01m}[39;00m[33m"[39m,
[32m    403[39m         name=[38;5;28;01mNone[39;00m
[32m    404[39m     )
[32m    406[39m [38;5;28;01mif[39;00m attr == [33m"[39m[33mchararray[39m[33m"[39m:
[32m    407[39m     warnings.warn(
[32m    408[39m         [33m"[39m[33m`np.chararray` is deprecated and will be removed from [39m[33m"[39m
[32m    409[39m         [33m"[39m[33mthe main namespace in the future. Use an array with a string [39m[33m"[39m
[32m    410[39m         [33m"[39m[33mor bytes dtype instead.[39m[33m"[39m, [38;5;167;01mDeprecationWarning[39;00m, stacklevel=[32m2[39m)

[31mAttributeError[39m: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

